### ISSUE TITLE
Feature request: whammy modulation

### ISSUE THREAD

**Issue by ucbmusictreasurer** [YARC-Official/YARG#786] opened 2024-05-28 23:03 UTC
On multitracks where we have an isolated guitar channel, can we have the return of the whammy modulation? It would be great to have an option for a number of semitones to modulate through. I believe the default from the official games was either 1 or 2 semitones.

**Comment by jbienz** [comment] 2024-07-01 06:28
@TheNathannator and @RileyTheFox, I was wondering if either of you could comment on what went wrong with whammy modulation in the past? I see https://github.com/YARC-Official/YARG/pull/487 and https://github.com/YARC-Official/YARG/pull/513 as attempts, but it appears they were rolled back.

I believe I may have fully implemented it tonight, though this is my first attempt at modifying the YARG codebase. I did connect it up to FiveFretPlayer and updated existing features that were there but commented out.

My two pull requests for this feature are:

**YARG.Core:** https://github.com/YARC-Official/YARG.Core/pull/192

**YARG Front End:** https://github.com/YARC-Official/YARG/pull/812

These PR's include details on what was changed / added. Probably the most controversial change is updating **WHAMMY_FFT_DEFAULT** in **GlobalAudioHandler** to 512 in an attempt to reduce latency between the guitar track and other tracks when pitch change is enabled. I am aware that there are notes mentioning that changing the FFT size causes BASS to crash, but I was not able to reproduce that. I don't know if the BASS version has been updated in this past year. I can of course remove this change. Another option would be to remove the pitch filter after whammy has been sitting at 0 for a period of time, but I couldn't figure out how to get an update tick in FiveFretPlayer.

I will join the Discord server to make it easier to discuss this PR there.

**Comment by RileyTheFox** [comment] 2024-08-20 00:20
This has been merged to our `engine-refactor` branch. It has been added behind an experimental features settings tab and disabled by default. It will be in the nightly version when we push v0.13 to nightly in about a month

**Closed by RileyTheFox** 2024-08-20 00:20 UTC
