### ISSUE TITLE
YARG not disabling Harmonies in menu properly when no harmonies are present

### ISSUE THREAD

**Issue by qfoxb** [YARC-Official/YARG#425] opened 2023-06-05 02:58 UTC
YARG v0.10.5
Culprit song is a CON, Vocals bar looks like this and never earns any score. Occasionally, the microphone cursor will move a bunch and then go back down. 
![image](https://github.com/YARC-Official/YARG/assets/42038239/ab5955ee-dd2a-4506-ba8f-0e59b11462f9)
Attached below is log
[Player.log](https://github.com/YARC-Official/YARG/files/11648126/Player.log) (12MB)

Error:
```ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <88e4733ac7bc4ae1b496735e6b83bbd3>:0 
  at YARG.PlayMode.MicPlayer.OnSongStart () [0x0015a] in <1f8871d8b5694145b97f6132f92e6dd4>:0 
  at YARG.PlayMode.MicPlayer.Update () [0x00029] in <1f8871d8b5694145b97f6132f92e6dd4>:0 

NullReferenceException: Object reference not set to an instance of an object
  at YARG.PlayMode.MicPlayer.Update () [0x00647] in <1f8871d8b5694145b97f6132f92e6dd4>:0 
```

**Comment by TheNathannator** [comment] 2023-06-05 17:58
Which song specifically is causing the issue? This'll be difficult to track down without replicating it locally, there's a good number of spots in the code that could be causing the error.

**Comment by qfoxb** [comment] 2023-06-05 18:19
> Which song specifically is causing the issue? This'll be difficult to track down without replicating it locally, there's a good number of spots in the code that could be causing the error.

If you'd like, I can send the CON without any audio due to copyright

**Comment by qfoxb** [comment] 2023-06-05 18:26
Sextape by Deftones

**Comment by TheNathannator** [comment] 2023-06-05 20:03
Looks like the issue is YARG isn't disabling Harmonies when no harmony tracks are present, working on a fix for that now.

**Comment by EliteAsian123** [comment] 2023-06-25 01:16
This is now fixed.

**Closed by EliteAsian123** 2023-06-25 01:16 UTC
